ci(twospaceships): replace npm audit with dependency review action
Signed-off-by: Sofian-bll <Sofianebelloul@gmail.com>

diff --git a/.github/workflows/ci-two-spaceships.yml b/.github/workflows/ci-two-spaceships.yml
--- a/.github/workflows/ci-two-spaceships.yml
+++ b/.github/workflows/ci-two-spaceships.yml
@@ -117,14 +117,21 @@ jobs:
         with:
           working-directory: ${{ env.WORK_DIR }}
 
-      - name: Run npm audit
-        id: audit
-        working-directory: ${{ env.WORK_DIR }}
-        run: npm audit --audit-level high
-        continue-on-error: true
-        env:
-          CI: true
+#      - name: Run npm audit
+#        id: audit
+#        working-directory: ${{ env.WORK_DIR }}
+#        run: npm audit --audit-level high
+#        continue-on-error: true
+#        env:
+#          CI: true
 
-      - name: Fail job if audit failed
-        if: steps.audit.outcome == 'failure'
-        run: exit 1
+      - name: 'Audit Dependency'
+        uses: actions/dependency-review-action@v4
+        with:
+          fail-on-severity: high
+          comment-summary-in-pr: on-failure
+
+#
+#      - name: Fail job if audit failed
+#        if: steps.audit.outcome == 'failure'
+#        run: exit 1
